// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Project struct {
	ID          int32
	Name        string
	Status      string
	Link        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectVersion struct {
	ID          int32
	ProjectID   int32
	Version     string
	Description string
	CreatedAt   time.Time
}

type ProjectVersionService struct {
	ProjectVersionID int32
	ServiceID        int32
	ServiceVersionID int32
}

type Service struct {
	ID          int32
	ProjectID   int32
	Name        string
	Status      string
	Description string
	RepoUrl     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ServiceVersion struct {
	ID          int32
	ServiceID   int32
	Version     string
	Status      string
	GitHash     string
	Description string
	CreatedAt   time.Time
}
