// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package database

import (
	"context"
	"time"
)

const checkServiceExistsByName = `-- name: CheckServiceExistsByName :one
SELECT EXISTS (
    SELECT 1 FROM services
    WHERE name = $1 AND project_id = $2
) AS exists
`

type CheckServiceExistsByNameParams struct {
	Name      string
	ProjectID int32
}

func (q *Queries) CheckServiceExistsByName(ctx context.Context, arg CheckServiceExistsByNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkServiceExistsByName, arg.Name, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (project_id, name, status, description, repo_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, status, description, repo_url, created_at, updated_at
`

type CreateServiceParams struct {
	ProjectID   int32
	Name        string
	Status      string
	Description string
	RepoUrl     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.ProjectID,
		arg.Name,
		arg.Status,
		arg.Description,
		arg.RepoUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectServiceByName = `-- name: DeleteProjectServiceByName :one
DELETE FROM services
WHERE name = $1 AND project_id = $2
RETURNING id, project_id, name, status, description, repo_url, created_at, updated_at
`

type DeleteProjectServiceByNameParams struct {
	Name      string
	ProjectID int32
}

func (q *Queries) DeleteProjectServiceByName(ctx context.Context, arg DeleteProjectServiceByNameParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, deleteProjectServiceByName, arg.Name, arg.ProjectID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectServiceByStatus = `-- name: GetProjectServiceByStatus :many
SELECT id, project_id, name, status, description, repo_url, created_at, updated_at FROM services
WHERE project_id = $1 AND status = $2
ORDER BY name
`

type GetProjectServiceByStatusParams struct {
	ProjectID int32
	Status    string
}

func (q *Queries) GetProjectServiceByStatus(ctx context.Context, arg GetProjectServiceByStatusParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getProjectServiceByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByProjectName = `-- name: GetServiceByProjectName :many
SELECT id, project_id, name, status, description, repo_url, created_at, updated_at FROM services
WHERE project_id = (
  SELECT id FROM projects WHERE projects.id = $1
)
ORDER BY name
`

func (q *Queries) GetServiceByProjectName(ctx context.Context, projectID int32) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServiceByProjectName, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Status,
			&i.Description,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getserviceById = `-- name: GetserviceById :one
SELECT id, project_id, name, status, description, repo_url, created_at, updated_at FROM services
WHERE id = $1
`

func (q *Queries) GetserviceById(ctx context.Context, id int32) (Service, error) {
	row := q.db.QueryRowContext(ctx, getserviceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getserviceByName = `-- name: GetserviceByName :one
SELECT id, project_id, name, status, description, repo_url, created_at, updated_at FROM services
WHERE name = $1 AND project_id = $2
LIMIT 1
`

type GetserviceByNameParams struct {
	Name      string
	ProjectID int32
}

func (q *Queries) GetserviceByName(ctx context.Context, arg GetserviceByNameParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, getserviceByName, arg.Name, arg.ProjectID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceStatus = `-- name: UpdateServiceStatus :exec
UPDATE services
SET status = $2, updated_at = $3
WHERE id = $1
`

type UpdateServiceStatusParams struct {
	ID        int32
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
