---
services:
  postgres:
    image: docker.io/postgres:16
    container_name: bosla_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: MyVeryStrongPassword
      POSTGRES_DB: bosla
    ports: [2345:5432]
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
